language: node_js
node_js:
  - 12
os:
  - linux
  - osx
services:
  - xvfb

install:
  - npm set progress=false
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - bash <(curl -s https://codecov.io/bash)
