export const DEFAULT_NOTIFICATION_CHANNELS = 'DEFAULT_NOTIFICATION_CHANNELS';
export const DEFAULT_QUICK_CHANNELS = 'DEFAULT_QUICK_CHANNELS';
export const DEFAULT_VOICE_CHANNELS = 'DEFAULT_VOICE_CHANNELS';
export const DISCORD_TOKEN = 'DISCORD_TOKEN';
export const GUILD_ID = 'GUILD_ID';
export const ALERT_INTERVAL = 'ALERT_INTERVAL';
